# Use uma imagem base leve
FROM python:3.9-slim

# Defina variáveis ​​de ambiente
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIP_ROOT_USER_ACTION=ignore

# Defina o diretório de trabalho
WORKDIR /code

# Copie os arquivos necessários
COPY . /code

# Instale as dependências e limpe a cache do gerenciador de pacotes
RUN apt-get update \
    && apt-get install -y --no-install-recommends cron \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt \
    && python manage.py migrate \
    && python manage.py crontab add \
    && apt-get remove -y cron \
    && apt-get autoremove -y \
    && apt-get clean

# Exponha a porta
EXPOSE 8080

# Comando que será executado na imagem
CMD ["python", "manage.py", "runserver", "0.0.0.0:8080", "api"]
