# Generated by Django 4.2.1 on 2023-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.CharField(max_length=10)),
                ('nome_reduzido', models.CharField(max_length=30)),
                ('numero_codigo', models.CharField(max_length=4)),
                ('participante_compensacao', models.CharField(max_length=4)),
                ('acesso_principal', models.CharField(max_length=4)),
                ('nome_extenso', models.CharField(max_length=100)),
                ('inicio_operacao', models.DateField()),
            ],
        ),
    ]
