# Generated by Django 4.2.1 on 2023-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_alter_banco_numero_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='inicio_operacao',
            field=models.CharField(max_length=30),
        ),
    ]
